export const UPDATE_USER_STORE = 'UPDATE_USER_STORE';

export const ADD_NEW_GROUP = 'ADD_NEW_GROUP';
export const CHOOSE_GROUP = 'CHOOSE_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const ADD_NEW_GRADIENT = 'ADD_NEW_GRADIENT';
export const DELETE_GRADIENT = 'DELETE_GRADIENT';

//dialogs
export const OPEN_NEW_GROUP_DIALOG = 'OPEN_NEW_GROUP_DIALOG';
export const CLOSE_NEW_GROUP_DIALOG = 'CLOSE_NEW_GROUP_DIALOG';

export const OPEN_NEW_GRADIENT_DIALOG = 'OPEN_NEW_GRADIENT_DIALOG';
export const CLOSE_NEW_GRADIENT_DIALOG = 'CLOSE_NEW_GRADIENT_DIALOG';
